name: Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  unit:
    name: PHPUnit unit tests - PHP ${{ matrix.php }}, Symfony ${{ matrix.symfony }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        php: ['8.0', '8.1']
        symfony: ['5.4.*', '6.0.*']

    runs-on: ${{ matrix.operating-system }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup php
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Download dependencies
        uses: php-actions/composer@v6
        with:
          php_version: ${{ matrix.php }}

      - name: Install specific symfony/console version
        uses: php-actions/composer@v6
        with:
          command: require
          php_version: ${{ matrix.php }}

      - name: Run PHPUnit unit tests
        run: composer test
